# Generated by Django 4.1.5 on 2023-01-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_post_published_at_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='post-default.jpg', upload_to='%Y/%m/%d'),
        ),
    ]
