# Generated by Django 4.1.5 on 2023-01-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile',
            field=models.ImageField(default='profile.svg', upload_to='%Y/%m/%d'),
        ),
    ]
